'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50215.44
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50215.44.
'
Namespace CalculateArea
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private RectangleAreaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = WebServTestBed.Settings.Default.WebServTestBed_CalculateArea_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event RectangleAreaCompleted As RectangleAreaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RectangleArea", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RectangleArea(ByVal length As Single, ByVal width As Single) As Single
            Dim results() As Object = Me.Invoke("RectangleArea", New Object() {length, width})
            Return CType(results(0),Single)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RectangleAreaAsync(ByVal length As Single, ByVal width As Single)
            Me.RectangleAreaAsync(length, width, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RectangleAreaAsync(ByVal length As Single, ByVal width As Single, ByVal userState As Object)
            If (Me.RectangleAreaOperationCompleted Is Nothing) Then
                Me.RectangleAreaOperationCompleted = AddressOf Me.OnRectangleAreaOperationCompleted
            End If
            Me.InvokeAsync("RectangleArea", New Object() {length, width}, Me.RectangleAreaOperationCompleted, userState)
        End Sub
        
        Private Sub OnRectangleAreaOperationCompleted(ByVal arg As Object)
            If (Not (Me.RectangleAreaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RectangleAreaCompleted(Me, New RectangleAreaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If (((wsUri.Port >= 1024)  _
                        AndAlso (wsUri.Port <= 5000))  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", true) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    Public Delegate Sub RectangleAreaCompletedEventHandler(ByVal sender As Object, ByVal e As RectangleAreaCompletedEventArgs)
    
    '''<remarks/>
    Partial Public Class RectangleAreaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Single
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Single)
            End Get
        End Property
    End Class
End Namespace
